### PR TITLE
Addition of US election Twitter seeds

### PR DESCRIPTION
**Pull request by anwala**
### 2020 US election Twitter seeds
Collection of seeds scraped from Twitter [Micro-collections](https://arxiv.org/abs/1905.12220) for the 2020 US elections with the query "election." Tweets were extracted from a Twitter account with trends location set to Norfolk, Virginia, USA. The tweets were posted between January 1, 2020 to October 2, 2020. The tweets were collected on October 2, 2020 by [Alexander Nwala](https://twitter.com/acnwala). No seeds were removed. The seeds are presented in three files:
 * [2020-election-tweet-seeds.txt](2020-election-tweet-seeds.txt): raw seeds extracted from tweets.
 * [2020-election-tweet-links.txt](2020-election-tweet-links.txt): the URI of the tweets containing the seeds.
 * [2020-election-seeds.json](2020-election-seeds.json): JSON file providing metadata for each seed such as the parent tweet details.

### CODE REVIEW

**Review by ldko — COMMENTED** [review]
Hi Alexander,
Thanks for contributing to the eot2020 end-of-term project. It's cool to see the results of some of your PhD work. Looking over the content, I think the URLs generally don't fit the [scope of the End of Term project](https://end-of-term.github.io/eotarchive/) which, rather than "election" related material, is website content created by the federal government (generally .gov/.mil sites) going so far as official social media accounts of members of the federal government.

Do you all have any thoughts on including these lists @vphill @freegovinfo @abgr  @Mr0grog ?

**Comment by vphill** [comment]
I would like to second the comments that @ldko made above. 

I think that these would fit better if we had the scope of the election in addition to the federal web, but sadly it is a bit outside of the scope of the End of Term project.

**Comment by Mr0grog** [comment]
Oooh, this is a really neat approach, but I do agree with @vphill and @ldko that it doesn’t fit the scope of End of Term very well. Maybe a subset of these that are just federal gov URLs or social media accounts would still fit?

Knowing @markjohngraham, though, I bet he’d love to get something like this feeding into the Wayback Machine as a separate effort from End of Term.

**Comment by freegovinfo** [comment]
I agree with what everyone said. and also as @Mr0grog  pointed out, I’m sure @markjohngraham and wayback could use these seeds regardless.

**Comment by anwala** [comment]
Hello all,

Thanks for the feedback. I was not fully aware of the scope before collecting these seeds. Taking a closer look at the eot2020 documentation. I agree with you. These seeds were collected to approximate the 2020 US election news cycle from the perspective news articles selected by social media users. That is why I sampled tweets from January to October, 2020.

**Comment by markjohngraham** [comment]
More seeds are good! :-)

**Comment by ldko** [comment]
Thanks, Alexander. I hope we see more of your work in the web archiving arena!

**Comment by anwala** [comment]
I hope so too. Thanks Lauren!

**Comment by ldko** [comment]
Note: Looking over the seeds presented in the files here when Sawood was compiling seeds for crawling, I pulled out a few that that looked in-scope and put them in the nomination tool: https://digital2.library.unt.edu/nomination/eth2020/reports/metadata/Comment/From%20Alexander%20Nwala%20via%20https://github.com/end-of-term/eot2020/pull/1/.

**Pull request closed without merging**
